@baseUrl=http://localhost:3002/api

PUT {{baseUrl}}/user
content-type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3IiOiJjb3JwIiwicm9sZSI6MiwiaWF0IjoxNjc1ODI4NDE2LCJleHAiOjE2NzU5MTQ4MTZ9.d0n7hTLePswdwB7d_PNFWuc1q_rH2vn6Gk7qKfPr9es

{
    "usr": "cus3",
    "pwd": "123456",
    "firstName": "customer",
    "lastName": "four",
    "role": 3
}